services:
    nginx:
        image: nginx:latest
        volumes:
            - ./:/var/www/
            - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
        ports:
            - "8811:80"
        depends_on:
            - app
        container_name: check_list_nginx
        networks:
            - check_list_network  # Добавляем сеть

    app:
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        volumes:
            - ./:/var/www/
        ports:
            - 5174:5174  # Пробрасываем порт 5174 с контейнера на хост
        depends_on:
            - db
        container_name: check_list_app
        networks:
            - check_list_network  # Добавляем сеть

    db:
        image: mysql:8.2
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: check_list
            MYSQL_ROOT_PASSWORD: root
        ports:
            - 3306:3306
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: check_list_db
        networks:
            - check_list_network  # Добавляем сеть

    vite:
        build:
            context: .
            dockerfile: _docker/vite/Dockerfile
        volumes:
            - ./:/var/www/
            - /var/www/node_modules
        ports:
            - "5173:5173"  # Пробрасываем порт Vite на хост
        container_name: check_list_vite
        working_dir: /var/www/
        command: sh -c "npm install && npm run dev"
        networks:
            - check_list_network
networks:
    check_list_network:
        driver: bridge  # Используем общую сеть
